# Practical No 3

* 1. Provide summary statistics (mean, median, minimum, maximum, standard deviation) for
a dataset (age, income etc.) with numeric variables grouped by one of the qualitative
(categorical) variable. For example, if your categorical variable is age groups and
quantitative variable is income, then provide summary statistics of income grouped by the
age groups. Create a list that contains a numeric value for each response to the categorical
variable.

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("loan_data_set.csv")

In [3]:
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [4]:
df.shape

(614, 13)

In [7]:
df.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [9]:
df.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [10]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [11]:
group = df.groupby('Gender')['ApplicantIncome']

In [12]:
group.mean()

Gender
Female    4643.473214
Male      5446.460123
Name: ApplicantIncome, dtype: float64

In [13]:
group.median()

Gender
Female    3583.0
Male      3865.0
Name: ApplicantIncome, dtype: float64

In [15]:
group.max()

Gender
Female    19484
Male      81000
Name: ApplicantIncome, dtype: int64

In [16]:
group.min()

Gender
Female    210
Male      150
Name: ApplicantIncome, dtype: int64

In [17]:
group.std()

Gender
Female    3585.381488
Male      6185.789262
Name: ApplicantIncome, dtype: float64

In [21]:
list_income = group.apply(list)
list_income

Gender
Female    [3510, 3750, 3667, 3410, 2645, 4000, 1928, 308...
Male      [5849, 4583, 3000, 2583, 6000, 5417, 2333, 303...
Name: ApplicantIncome, dtype: object

* 2. Write a Python program to display some basic statistical details like percentile, mean,
standard deviation etc. of the species of ‘Iris-setosa’, ‘Iris-versicolor’ and ‘Iris-versicolor’
of iris.csv dataset.

In [22]:
iris = pd.read_csv("Iris.csv")

In [38]:
df = pd.DataFrame(iris)
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [37]:
df.shape

(150, 6)

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [40]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [41]:
irisGroup= df.groupby('Species')

In [42]:
irisGroup

In [43]:
print(irisGroup.mean(numeric_only=True))

                    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Species
Iris-setosa       25.5          5.006         3.418          1.464
Iris-versicolor   75.5          5.936         2.770          4.260
Iris-virginica   125.5          6.588         2.974          5.552

                 PetalWidthCm
Species
Iris-setosa             0.244
Iris-versicolor         1.326
Iris-virginica          2.026

In [45]:
print(irisGroup.median(numeric_only=True))

                    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Species
Iris-setosa       25.5            5.0           3.4           1.50
Iris-versicolor   75.5            5.9           2.8           4.35
Iris-virginica   125.5            6.5           3.0           5.55

                 PetalWidthCm
Species
Iris-setosa               0.2
Iris-versicolor           1.3
Iris-virginica            2.0

In [46]:
print(irisGroup.std(numeric_only=True))

                       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  \
Species
Iris-setosa      14.57738       0.352490      0.381024       0.173511
Iris-versicolor  14.57738       0.516171      0.313798       0.469911
Iris-virginica   14.57738       0.635880      0.322497       0.551895

                 PetalWidthCm
Species
Iris-setosa          0.107210
Iris-versicolor      0.197753
Iris-virginica       0.274650

In [50]:
df.describe(percentiles=[0.25, 0.5, 0.75])

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [51]:
for name, data in irisGroup:

    print(f"\n==============================")
    print(f"Statistics for {name}")
    print(f"==============================")

    print("\nMean:\n")
    print(data.mean(numeric_only=True))

    print("\nMedian:\n")
    print(data.median(numeric_only=True))

    print("\nStandard Deviation:\n")
    print(data.std(numeric_only=True))

    print("\nPercentiles:\n")
    print(
        data.describe(percentiles=[0.25, 0.5, 0.75])
    )

==============================
Statistics for Iris-setosa
==============================

Mean:

Id               25.500
SepalLengthCm     5.006
SepalWidthCm      3.418
PetalLengthCm     1.464
PetalWidthCm      0.244
dtype: float64

Median:

Id               25.5
SepalLengthCm     5.0
SepalWidthCm      3.4
PetalLengthCm     1.5
PetalWidthCm      0.2
dtype: float64

Standard Deviation:

Id               14.577380
SepalLengthCm     0.352490
SepalWidthCm      0.381024
PetalLengthCm     0.173511
PetalWidthCm      0.107210
dtype: float64

Percentiles:

             Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  50.00000       50.00000     50.000000      50.000000      50.00000
mean   25.50000        5.00600      3.418000       1.464000       0.24400
std    14.57738        0.35249      0.381024       0.173511       0.10721
min     1.00000        4.30000      2.300000       1.000000       0.10000
25%    13.25000        4.80000      3.125000       1.400000       0.20000
50%    25.50000        5.00000      3.400000       1.500000       0.20000
75%    37.75000        5.20000      3.675000       1.575000       0.30000
max    50.00000        5.80000      4.400000       1.900000       0.60000

==============================
Statistics for Iris-versicolor
==============================

Mean:

Id               75.500
SepalLengthCm     5.936
SepalWidthCm      2.770
PetalLengthCm     4.260
PetalWidthCm      1.326
dtype: float64

Median:

Id               75.50
SepalLengthCm     5.90
SepalWidthCm      2.80
PetalLengthCm     4.35
PetalWidthCm      1.30
dtype: float64

Standard Deviation:

Id               14.577380
SepalLengthCm     0.516171
SepalWidthCm      0.313798
PetalLengthCm     0.469911
PetalWidthCm      0.197753
dtype: float64

Percentiles:

              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000      50.000000     50.000000      50.000000     50.000000
mean    75.50000       5.936000      2.770000       4.260000      1.326000
std     14.57738       0.516171      0.313798       0.469911      0.197753
min     51.00000       4.900000      2.000000       3.000000      1.000000
25%     63.25000       5.600000      2.525000       4.000000      1.200000
50%     75.50000       5.900000      2.800000       4.350000      1.300000
75%     87.75000       6.300000      3.000000       4.600000      1.500000
max    100.00000       7.000000      3.400000       5.100000      1.800000

==============================
Statistics for Iris-virginica
==============================

Mean:

Id               125.500
SepalLengthCm      6.588
SepalWidthCm       2.974
PetalLengthCm      5.552
PetalWidthCm       2.026
dtype: float64

Median:

Id               125.50
SepalLengthCm      6.50
SepalWidthCm       3.00
PetalLengthCm      5.55
PetalWidthCm       2.00
dtype: float64

Standard Deviation:

Id               14.577380
SepalLengthCm     0.635880
SepalWidthCm      0.322497
PetalLengthCm     0.551895
PetalWidthCm      0.274650
dtype: float64

Percentiles:

              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000       50.00000     50.000000      50.000000      50.00000
mean   125.50000        6.58800      2.974000       5.552000       2.02600
std     14.57738        0.63588      0.322497       0.551895       0.27465
min    101.00000        4.90000      2.200000       4.500000       1.40000
25%    113.25000        6.22500      2.800000       5.100000       1.80000
50%    125.50000        6.50000      3.000000       5.550000       2.00000
75%    137.75000        6.90000      3.175000       5.875000       2.30000
max    150.00000        7.90000      3.800000       6.900000       2.50000